# Generated by Django 4.1 on 2022-09-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('mobileno', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
